#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

PGDATABASE="${1}"
PGUSER="${PGDATABASE}"
PGPASS="${PGDATABASE}"

psql -U postgres -c "CREATE DATABASE ${PGDATABASE};"
psql -U postgres -c "CREATE ROLE ${PGUSER} LOGIN ENCRYPTED PASSWORD '$PGPASS' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;" ${PGDATABASE}
